name: Push to main

on:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: kiloexabyte/runner-image
    steps:
    - uses: actions/checkout@v4
    - run: | 
        go build 
    